/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor */

#ifndef _Included_org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor
#define _Included_org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor
 * Method:    sensorsInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor_sensorsInit
  (JNIEnv *, jclass);

/*
 * Class:     org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor
 * Method:    sensorsCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor_sensorsCleanup
  (JNIEnv *, jclass);

/*
 * Class:     org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor
 * Method:    getChipNames
 * Signature: ()[Lorg/example/sensemon/application/model/DeviceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor_getChipNames
  (JNIEnv *, jclass);

/*
 * Class:     org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor
 * Method:    getChipFeatures
 * Signature: (Lorg/example/sensemon/application/model/DeviceInfo;)[Lorg/example/sensemon/application/model/FeatureInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_org_example_sensemon_application_adapter_secondary_jni_JniSensorMonitor_getChipFeatures
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
